token: OTg1MzgZE3cwNDQyMTF67TU5.GFl0nX.WeyI8vqX3yO6kqh8Oia6cDpgEkZ1zH6eNHN9w8
refresh_time: 900
game_displayed: Eating some RSS feeds
twitter:
  enabled: True
  bearer_token: API_TOKEN_GOES_HERE
reddit:
  enabled: True
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  password: USER_PWD
  username: USERNAME