version: "3.9"
services:

  bot:
    build: discord_bot/
    restart: on-failure
    configs:
      - source: discord_bot_config_file
        target: /config/
    depends_on:
      - scrape2rss
    volumes:
      - backups:/home/rssbot/backups/

  scrape2rss:
    build: scrape2RSS/
    restart: on-failure

configs:
  discord_bot_config_file:
    file: ./config_file_goes_in_here

volumes:
  backups: