version: "3.9"
services:
  bot:
    image: rssbot
    restart: on-failure
    configs:
      - source: discord_bot_config_file
        target: /config/
    depends_on:
      - scrape2rss
  scrape2rss:
    image: scrape2rss
    restart: on-failure
configs:
  discord_bot_config_file:
    file: ./config_file
