version: "3.9"
services:
  bot:
    image: rssbot
    restart: on-failure
    configs:
      - source: discord_bot_config_file
        target: /config/config.json

  api:
    image: scrape2rss
    restart: on-failure
    ports:
      - "9292:9292"

configs:
  discord_bot_config_file:
    file: ./config.json
